### ISSUE TITLE
Prevent administrative area defaults from being populated in other threads

### ISSUE THREAD

**Issue by mattfff** [asmallwebfirm/scale_addressfield#7]
First off, I really appreciate your excellent work on this module, we ran into this in production and this really saved us. The one thing we continued to run into, though, was this:

When a country was selected (i.e. United States), and then a state was selected (i.e. California), and the form was submitted incompletely triggering validation errors, subsequent visits to the same page in another browser would yield "California" being selected by default when United States was selected as a country. This is presumably due to the same cached form being used, so since United States matched what was already cached, it "pre-selected" California. This is more annoying than anything, as in production it creates somewhat arbitrary "defaults" for states based on the form cache updated by other users.

Is this the purpose of the "healer" branch you are working on? Or is that designed to pick up edge cases where the form cache has expired a form, but the page is still making AJAX requests based on that stale form ID, thus preventing the address field from rebuilding as expected?

Thanks again... This module (and the issues it raises) really seems like something that should be put up in big red text on the addressfield project page, as any use of this module on a site gathering anonymous data is going to quickly have all kinds of trouble. Drupal anonymous AJAX handling seems generally broken given the form cache lifetime issue, leading me to wonder if it wouldn't be smarter to avoid it in anonymous, cached situations...

**Comment by iamEAP** [comment]
Thanks @mattfff!  Definitely agreed on the fundamental issues surrounding unauthenticated AJAX handling in Drupal; particularly with regard to Addressfield.  Longer term, we're looking at writing a JS-only (non-AJAX) plugin for addressfield to get around this issue entirely (the DB schema is great; it's just the AJAX functionality that's painful).

In the near-term, the healer branch (for #4), is for the exact edge-case you described (form cache is pulled out from underneath page cache, which continues to live).  Sounds like what you're experiencing is different, although I'm not sure I completely follow...  Here's my understanding:
1. User A visits a page with a form _/user_; the default country is US.
2. User A selects a state, _CA_, submits an incomplete form, returning validation errors.
3. User A abandons the form / page.
4. User B visits the same form page _/user_; the default country is US, and the default country State is CA?

I'm not sure I follow because User B should see the form as it was originally rendered by User A.  There would be a mismatch between what's rendered (on the page) and what's stored (in cache_form), but it should display fine.

Could you clarify?

**Comment by mattfff** [comment]
Thanks for responding so fast! I'd definitely love to see a client-side-only solution to this problem... 

Your sequence was almost spot on, except that you are indeed correct that user B sees a fully blank form when they arrive as expected, as that's what's cached by Drupal. In our case we are using a patch to also have the country select empty by default as well, as the customer didn't want the US to be the default. Sorry, should have mentioned that...

So, to clarify the sequence:
1. User A visits a page with a form /user; the default country is none.
2. User A selects the US.
3. The user sees a state list with "--" as the default, then selects CA, submits an incomplete form, returning validation errors.
4. User A abandons the form /user page. (or user B visits the page and starts interacting while User A is still fixing validation errors)
5. User B visits the same form page /user; selects US, and then the default state is pre-selected to be CA based on user A's previous actions.

This has been somewhat intermittent in production, but I have duplicated it locally in my dev copy. What's doubly odd about it is that we have two addressfields on the same page, and this only seems to happen to the first one. So perhaps it's an entirely unrelated issue, but I thought it was worth mentioning.

Thanks again!

**Comment by iamEAP** [comment]
Ah, now I understand. Seems like the default-to-no-country patch you're running is exacerbating the problems this module tries to resolve (because _every single form submission_ requires AJAX interaction, which is going to bring up the number of collisions substantially).

We were able to work around that scenario by making a small configuration change (no patch) to force the address field to default to the site default country--a variable that we have configured differently (read: "translated") per language.

If that doesn't fit your use-case...  It's going to be difficult.  This module is definitely the place to make it happen, though.  Perhaps you can borrow concepts from / build on top of the healer stuff.  It might also be possible somewhere in the form validation layer.

This is definitely employer-sponsored work on my part; since we're not directly affected, I won't be able to spend substantial time on it.  I'd be more than happy to review / collaborate on a contribution, though!

**Comment by mattfff** [comment]
Thanks for the response! Happily, it looks like this should all be addressed by https://drupal.org/SA-CORE-2014-002. The API change to ajax_get_form means that the form_build_id is updated via AJAX on forms loaded from the anonymous page cache, which should fix the conflicts with multiple users using the same form_build_id via the page cache. What I reported above really was a type of info disclosure (though I didn't think of it), so it was a manifestation of the issue fixed in the SA. I don't see that this issue will require any updates to addressfield itself, though I haven't tested it yet. They took a very similar approach to your healer script, updating the form_build_id with a fresh one via AJAX.

**Comment by iamEAP** [comment]
Yes on all accounts!  Drupal 7.27 addresses this issue with no need to update Address Field.  See: https://drupal.org/node/1861608

I believe the healer that was introduced in the latest release of this module may still address an extremely edge-case usability issue (where a user stays on a page / leaves a tab open for over 6 hours before engaging with the form)...  But if that's not a concern for you, you can probably disable/uninstall Scale Addressfield completely.

Beyond the information disclosure vulnerability, Address Field--and all AJAX enabled Drupal forms--still pose a significant performance/scalability bottleneck to Drupal, so I'm still working full steam on a 7.x-2.x version of this module that moves country-based dynamic behavior completely to the client-side.  Expect something in that area soon.

For now, I'll close this and advise anyone who finds their way here to update to Drupal 7.27.
